[build]
  publish = "dist/"
  command = "npm run build"

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/assets/*"

  [headers.values]
    # Assets include checksum in the name, so we cache them for long
    Cache-Control = "public, max-age=31536000"
